"""
Creates the Lagrangian structure geometry for a finray tail and writes the
associated input files (.vertex, .geo_connect, .spring, .beam, .target).
"""

import numpy as np
import matplotlib.pyplot as plt
import json, os

_case_params = {}
if os.path.exists('case_params.json'):
    with open('case_params.json') as f:
        _case_params = json.load(f)
_geom = _case_params.get('geom', {})


def FinRay_Geom():
    # Eulerian grid params (MAKE SURE MATCHES THOSE IN input2d !!!)
    Nx = 32           # MUST BE EVEN!!!
    Lx = 1.0          # length of grid in x-direction
    dx = Lx / Nx      # spatial resolution

    # Immersed structure geometric / dynamic params
    ds = 0.5 * dx               # Lagrangian point spacing (2x resolution of Eulerian grid!!!)
    struct_name = 'finray'    # name for .vertex, .spring, etc files (must match what's in 'input2d')

    # Construct geometry (also returns which indices belong to the outline vs. each ray, needed to
    # wire up connections correctly below)
    xLag, yLag, outlineIdx, rayIdxList, baseCornerIdx = _Build_Tail_Geometry(ds)

    # Plot geometry to test
    connections = build_Tail_Connections(xLag, yLag, outlineIdx, rayIdxList)
    for (i, j, kind) in connections:
        plt.plot([xLag[i], xLag[j]], [yLag[i], yLag[j]], 'b-', linewidth=0.75)
    plt.plot(xLag[outlineIdx], yLag[outlineIdx], 'r*')
    for ray in rayIdxList:
        plt.plot(xLag[ray], yLag[ray], 'g*')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.axis('square')
    plt.show()

    # Print .vertex file
    print_Lagrangian_Vertices(xLag, yLag, struct_name)

    # Print .geo_connect file
    print_Geometry_Connections(connections, struct_name)

    #-------------------------------------------------------------------
    # Material properties - trying to mimick real system from dimensions and Dragon Skin 30 
    # silicone properties
    # NOTE: Will try to implement finer sampling down the line
    #-------------------------------------------------------------------
    E_material = _geom.get('E_material', 0.74e6)
    wall_thickness = _geom.get('wall_thickness', 0.00396)   # m (3.96mm in real build)
    extrude_depth = _geom.get('extrude_depth', 0.05)        # m

    # Print .spring file
    #   k_Spring: real material stiffness, from E/A/ds above.
    #   k_Attach: ray-to-rail junction springs - play around to see how tail flap is affected by making these stiffer or softer than the material itself.
    k_Spring = spring_Stiffness_From_Material(E_material, wall_thickness, extrude_depth, ds)
    k_Attach = 50.0 * k_Spring
    print_Lagrangian_Springs(xLag, yLag, connections, k_Spring, k_Attach, struct_name)

    # Print .beam file
    #   k_Beam: from EI/ds
    k_Beam = beam_Stiffness_From_Material(E_material, wall_thickness, extrude_depth, ds)
    beams = build_Tail_Beams(outlineIdx, rayIdxList)
    print_Lagrangian_Beams(xLag, yLag, beams, k_Beam, struct_name)

    # Print .target file
    #   k_Target is set to very high to hold the points nearly rigid.
    k_Target = 1000.0 * k_Spring
    print_Lagrangian_Target_Pts(list(baseCornerIdx), k_Target, struct_name)



def print_Lagrangian_Vertices(xLag, yLag, struct_name):
    '''
    Prints the Lagrangian points to .vertex file.

    xLag: x-coordinates of Lagrangian points
    yLag: y-coordinates of Lagrangian points
    '''
    N = len(xLag)  # total num of Lagrangian points

    with open(struct_name + '.vertex', 'w') as f:
        f.write('%d\n' % N)
        # Loops over all points
        for s in range(N):
            f.write('%1.16e %1.16e\n' % (xLag[s], yLag[s]))

def print_Geometry_Connections(connections, struct_name):
    '''
    Prints the connections to .geo_connect file.
    
    connections: list of (i, j, kind) generated by build_Tail_Connections()
    '''
    with open(struct_name + '.geo_connect', 'w') as f:
        for (i, j, kind) in connections:
            s1, s2 = i, j
            f.write('%d %d\n' % (s1, s2))
            f.write('%d %d\n' % (s2, s1))

def print_Lagrangian_Springs(xLag, yLag, connections, k_Spring, k_Attach, struct_name, deg_NL=1.0):
    '''
    Prints springs to .spring file.
    
    connections: list of (i, j, kind) generated by build_Tail_Connections()
    k_Spring: spring constant for the material
    k_Attach: spring constant for the attachments
    struct_name: name of the structure
    deg_NL: degree of nonlinearity
    '''
    N = len(connections)

    with open(struct_name + '.spring', 'w') as f:
        f.write('%d\n' % N)   # Print # of springs

        for (i, j, kind) in connections:
            ds_Rest = float(np.hypot(xLag[j] - xLag[i], yLag[j] - yLag[i])) # set initial distance as resting length
            k = k_Attach if kind == 'attach' else k_Spring # fused junctions get stiffer springs
            f.write('%d %d %1.16e %1.16e %1.16e\n' % (i, j, k, ds_Rest, deg_NL))

def print_Lagrangian_Target_Pts(target_indices, k_Target, struct_name):
    '''
    Prints the target points to .target file.

    target_indices: list of 0-indexed points to actuate
    k_Target: spring constant for the target points
    '''
    N = len(target_indices)

    with open(struct_name + '.target', 'w') as f:
        f.write('%d\n' % N)
        for idx in target_indices:
            f.write('%d %1.16e\n' % (idx, k_Target))

def print_Lagrangian_Beams(xLag, yLag, beams, k_Beam, struct_name):
    '''
    Prints the beams to .beam file.

    beams: list of (L, M, R) 0-indexed point-index triples generated by build_Tail_Beams()
    k_Beam: beam stiffness
    '''
    N = len(beams)

    with open(struct_name + '.beam', 'w') as f:
        f.write('%d\n' % N)

        for (L, M, R) in beams:
            Xp, Yp = xLag[L], yLag[L]
            Xq, Yq = xLag[M], yLag[M]
            Xr, Yr = xLag[R], yLag[R]
            C = (Xr - Xq) * (Yq - Yp) - (Yr - Yq) * (Xq - Xp)  # curvature (signed area of triangle formed by the three points L, M, R)
            f.write('%d %d %d %1.16e %1.16e\n' % (L, M, R, k_Beam, C))



def spring_Stiffness_From_Material(E, thickness, depth, ds):
    """
    Converts a material's Young's modulus into IB2d's discrete spring
    stiffness, treating each spring as an axial rod segment of rest
    length ds and cross-sectional area (thickness x depth):

        k = E * A / ds      (standard truss-element axial stiffness)

    E:  Young's modulus, Pa. NOTE: silicone is hyperelastic (nonlinear
        stress-strain), so a single E is a linear approximation.
    thickness: wall thickness in the plane of the 2D approximation, m.
    depth: out-of-plane extrusion depth, m.
    ds: current Lagrangian point spacing (hence why k_Spring is recomputed 
        if Nx/Lx is changed, rather than hardcoded).
    """
    A = thickness * depth
    return E * A / ds


def beam_Stiffness_From_Material(E, thickness, depth, ds):
    """
    Converts a material's Young's modulus into IB2d's discrete beam
    (torsional spring) stiffness, using the standard scaling for a
    discretized beam approximating a continuum flexural rigidity EI:

        I = thickness^3 * depth / 12   (rectangular cross-section,
                                         thickness in the bending direction)
        k_Beam = E * I / ds

    NOTE: IB2d's torsional spring energy is defined via a signed-area
    form of "curvature" rather than a normalized curvature. Might have to
    verify that the scaling of k_Beam with E and I is correct for IB2d's
    discrete implementation.
    """
    I = (thickness ** 3) * depth / 12.0
    return E * I / ds


def build_Tail_Beams(outlineIdx, rayIdxList):
    '''
    Builds the list of (left, middle, right) 0-indexed point-index
    triples that get bending resistance. 
    Same piece-aware logic as build_Tail_Connections: the outline is 
    a closed loop (wraps around), each ray is an open chain (does not), 
    and rays get no bending connection to each other.

    NOTE: this does not add a beam spanning the
    ray-to-outline junction itself, so bending moment isn't transmitted
    across that connection (only the axial attachment spring force is
    via build_Tail_Connections). The junction currently behaves like a hinge
    instead of a fused connection.
    '''

    beams = []

    # Outline: closed loop, one beam centered at every point
    No = len(outlineIdx)
    for i in range(No):
        L = outlineIdx[(i - 1) % No]
        M = outlineIdx[i]
        R = outlineIdx[(i + 1) % No]
        beams.append((L, M, R))

    # Each ray: open chain, only interior points get a beam
    for ray in rayIdxList:
        for i in range(1, len(ray) - 1):
            beams.append((ray[i - 1], ray[i], ray[i + 1]))

    return beams


def give_Me_Immersed_Boundary_Geometry(ds, Nx):
    '''
    Returns the Lagrangian coordinates of the immersed boundary geometry.

    ds: Lagrangian point spacing
    Nx: Eulerian grid resolution
    '''

    xLag, yLag, _, _, _ = _Build_Tail_Geometry(ds)
    return xLag, yLag


def build_Tail_Connections(xLag, yLag, outlineIdx, rayIdxList):
    '''
    Builds the list of (i, j, kind) triples.
    kind is one of:
      'outline': the closed outline loop (last point wraps to first).
      'ray':     each ray's open internal chain.
      'attach':  each ray's two endpoints connected to their nearest
                 outline point.

    kind is returned explicitly so the caller can give 'attach' springs
    a different (stiffer) constant.
    '''

    connections = []

    # Outline: closed loop
    No = len(outlineIdx)
    for k in range(No):
        i = outlineIdx[k]
        j = outlineIdx[(k + 1) % No]     # wraps last -> first, closing the loop
        connections.append((i, j, 'outline'))

    # Each ray: open chain (no wraparound and no cross-ray links)
    for ray in rayIdxList:
        for k in range(len(ray) - 1):
            connections.append((ray[k], ray[k + 1], 'ray'))

    # Attach each ray's endpoints to their nearest outline point
    outline_xy = np.column_stack((xLag[outlineIdx], yLag[outlineIdx]))
    for ray in rayIdxList:
        for endpoint in (ray[0], ray[-1]):
            p = np.array([xLag[endpoint], yLag[endpoint]])
            dists = np.linalg.norm(outline_xy - p, axis=1)
            nearest_idx = outlineIdx[int(np.argmin(dists))]
            connections.append((endpoint, nearest_idx, 'attach'))

    return connections


def _Build_Tail_Geometry(ds):
    # !Provide real tail geometry here! (same units as Lx, Ly in input2d)
    L = 0.136   # Tail length
    W = 0.051   # Base width

    # Distance of each ray from the base, measured along the tail's length.
    rayPositions = [0.025, 0.047, 0.069, 0.091]

    # Position of the base's midpoint within the computational domain.
    x0 = 0.3    # x-location of the base
    y0 = 0.5    # y-location of the base's midpoint

    # Half-width of the triangle at distance d from the base
    def halfWidth(d):
        return (W / 2) * (1 - d / L)

    xLag = []
    yLag = []

    # Outline: base -> top slanted edge -> bottom slanted edge
    # (traversed so shared corner points aren't duplicated; the loop is
    # closed later in build_Tail_Connections)
    # --- Base (short side), vertical segment at x = x0
    nBase = max(round(W / ds), 2)
    yBase = np.linspace(y0 - W / 2, y0 + W / 2, nBase)
    xBase = x0 * np.ones_like(yBase)
    xLag.extend(xBase)
    yLag.extend(yBase)

    # --- Top slanted edge: base-top corner -> tip
    topStart = np.array([x0, y0 + W / 2])
    tip = np.array([x0 + L, y0])
    nTop = max(round(np.linalg.norm(tip - topStart) / ds), 2)
    xTop = np.linspace(topStart[0], tip[0], nTop)
    yTop = np.linspace(topStart[1], tip[1], nTop)
    xLag.extend(xTop[1:])        # drop shared corner
    yLag.extend(yTop[1:])

    # --- Bottom slanted edge: tip -> base-bottom corner
    botEnd = np.array([x0, y0 - W / 2])
    nBot = max(round(np.linalg.norm(botEnd - tip) / ds), 2)
    xBot = np.linspace(tip[0], botEnd[0], nBot)
    yBot = np.linspace(tip[1], botEnd[1], nBot)
    xLag.extend(xBot[1:-1])      # drop both shared corners
    yLag.extend(yBot[1:-1])

    outlineIdx = list(range(len(xLag)))   # every point so far belongs to the outline

    # The two base corners, by global index, which are needed for actuation
    # (target points) later. baseBottomIdx is the very first point added
    # (start of the base segment); baseTopIdx is the last point of the
    # base segment, i.e. index nBase-1, before the top edge begins.
    baseBottomIdx = 0
    baseTopIdx = nBase - 1
    baseCornerIdx = (baseBottomIdx, baseTopIdx)

    # 4 internal rays, each parallel to the base.
    # Each ray's indices are tracked separately (rayIdxList) so that
    # build_Tail_Connections can keep them as independent open chains
    # instead of accidentally chaining ray -> next ray.
    rayIdxList = []
    for d in rayPositions:
        hw = halfWidth(d)
        nRay = max(round((2 * hw) / ds), 2)
        yRay = np.linspace(y0 - hw, y0 + hw, nRay)
        xRay = (x0 + d) * np.ones_like(yRay)

        startIdx = len(xLag)
        xLag.extend(xRay)
        yLag.extend(yRay)
        rayIdxList.append(list(range(startIdx, len(xLag))))

    xLag = np.array(xLag)
    yLag = np.array(yLag)

    return xLag, yLag, outlineIdx, rayIdxList, baseCornerIdx


if __name__ == "__main__":
    FinRay_Geom()