# --- Legacy (single-point-thick) implementation, kept for reference -------
#
# def print_Lagrangian_Springs(xLag, yLag, connections, k_Spring, k_Attach, struct_name, deg_NL=1.0):
#     '''
#     Prints springs to .spring file.
#
#     connections: list of (i, j, kind) generated by build_Tail_Connections()
#     k_Spring: spring constant for the material
#     k_Attach: spring constant for the attachments
#     struct_name: name of the structure
#     deg_NL: degree of nonlinearity
#     '''
#     N = len(connections)
#
#     with open(struct_name + '.spring', 'w') as f:
#         f.write('%d\n' % N)   # Print # of springs
#
#         for (i, j, kind) in connections:
#             ds_Rest = float(np.hypot(xLag[j] - xLag[i], yLag[j] - yLag[i])) # set initial distance as resting length
#             k = k_Attach if kind == 'attach' else k_Spring # fused junctions get stiffer springs
#             f.write('%d %d %1.16e %1.16e %1.16e\n' % (i, j, k, ds_Rest, deg_NL))
#
# ---------------------------------------------------------------------------

# --- Legacy (single-point-thick) implementation, kept for reference -------
#
# def build_Tail_Beams(frameIdx, rayIdxList):
#     '''
#     Builds the list of (left, middle, right) 0-indexed point-index
#     triples that get bending resistance.
#     Same piece-aware logic as build_Tail_Connections: the frame is
#     a closed loop (wraps around), each ray is an open chain (does not),
#     and rays get no bending connection to each other.
#
#     NOTE: this does not add a beam spanning the
#     ray-to-frame junction itself, so bending moment isn't transmitted
#     across that connection (only the axial attachment spring force is
#     via build_Tail_Connections). The junction currently behaves like a hinge
#     instead of a fused connection.
#     '''
#
#     beams = []
#
#     # Outline: closed loop, one beam centered at every point
#     No = len(frameIdx)
#     for i in range(No):
#         L = frameIdx[(i - 1) % No]
#         M = frameIdx[i]
#         R = frameIdx[(i + 1) % No]
#         beams.append((L, M, R))
#
#     # Each ray: open chain, only interior points get a beam
#     for ray in rayIdxList:
#         for i in range(1, len(ray) - 1):
#             beams.append((ray[i - 1], ray[i], ray[i + 1]))
#
#     return beams
#
# ---------------------------------------------------------------------------

# --- Legacy (single-point-thick) implementation, kept for reference -------
#
# def build_Tail_Connections(xLag, yLag, frameIdx, rayIdxList):
#     '''
#     Builds the list of (i, j, kind) triples.
#     kind is one of:
#       'frame': the closed frame loop (last point wraps to first).
#       'ray':     each ray's open internal chain.
#       'attach':  each ray's two endpoints connected to their nearest
#                  frame point.
#
#     kind is returned explicitly so the caller can give 'attach' springs
#     a different (stiffer) constant.
#     '''
#
#     connections = []
#
#     # Outline: closed loop
#     No = len(frameIdx)
#     for k in range(No):
#         i = frameIdx[k]
#         j = frameIdx[(k + 1) % No]     # wraps last -> first, closing the loop
#         connections.append((i, j, 'frame'))
#
#     # Each ray: open chain (no wraparound and no cross-ray links)
#     for ray in rayIdxList:
#         for k in range(len(ray) - 1):
#             connections.append((ray[k], ray[k + 1], 'ray'))
#
#     # Attach each ray's endpoints to their nearest frame point
#     frame_xy = np.column_stack((xLag[frameIdx], yLag[frameIdx]))
#     for ray in rayIdxList:
#         for endpoint in (ray[0], ray[-1]):
#             p = np.array([xLag[endpoint], yLag[endpoint]])
#             dists = np.linalg.norm(frame_xy - p, axis=1)
#             nearest_idx = frameIdx[int(np.argmin(dists))]
#             connections.append((endpoint, nearest_idx, 'attach'))
#
#     return connections
#
# ---------------------------------------------------------------------------

# --- Legacy (single-point-thick) implementation, kept for reference -------
#
# def _Build_Tail_Geometry(ds):
#     # !Provide real tail geometry here! (same units as Lx, Ly in input2d)
#     L = 0.136   # Tail length
#     W = 0.051   # Base width
#
#     # Distance of each ray from the base, measured along the tail's length.
#     rayPositions = [0.025, 0.047, 0.069, 0.091]
#
#     # Position of the base's midpoint within the computational domain.
#     x0 = 0.3    # x-location of the base
#     y0 = 0.5    # y-location of the base's midpoint
#
#     # Half-width of the triangle at distance d from the base
#     def halfWidth(d):
#         return (W / 2) * (1 - d / L)
#
#     xLag = []
#     yLag = []
#
#     # Outline: base -> top slanted edge -> bottom slanted edge
#     # (traversed so shared corner points aren't duplicated; the loop is
#     # closed later in build_Tail_Connections)
#     # --- Base (short side), vertical segment at x = x0
#     nBase = max(round(W / ds), 2)
#     yBase = np.linspace(y0 - W / 2, y0 + W / 2, nBase)
#     xBase = x0 * np.ones_like(yBase)
#     xLag.extend(xBase)
#     yLag.extend(yBase)
#
#     # --- Top slanted edge: base-top corner -> tip
#     topStart = np.array([x0, y0 + W / 2])
#     tip = np.array([x0 + L, y0])
#     nTop = max(round(np.linalg.norm(tip - topStart) / ds), 2)
#     xTop = np.linspace(topStart[0], tip[0], nTop)
#     yTop = np.linspace(topStart[1], tip[1], nTop)
#     xLag.extend(xTop[1:])        # drop shared corner
#     yLag.extend(yTop[1:])
#
#     # --- Bottom slanted edge: tip -> base-bottom corner
#     botEnd = np.array([x0, y0 - W / 2])
#     nBot = max(round(np.linalg.norm(botEnd - tip) / ds), 2)
#     xBot = np.linspace(tip[0], botEnd[0], nBot)
#     yBot = np.linspace(tip[1], botEnd[1], nBot)
#     xLag.extend(xBot[1:-1])      # drop both shared corners
#     yLag.extend(yBot[1:-1])
#
#     frameIdx = list(range(len(xLag)))   # every point so far belongs to the frame
#
#     # The two base corners, by global index, which are needed for actuation
#     # (target points) later. baseBottomIdx is the very first point added
#     # (start of the base segment); baseTopIdx is the last point of the
#     # base segment, i.e. index nBase-1, before the top edge begins.
#     baseBottomIdx = 0
#     baseTopIdx = nBase - 1
#     baseCornerIdx = (baseBottomIdx, baseTopIdx)
#
#     # 4 internal rays, each parallel to the base.
#     # Each ray's indices are tracked separately (rayIdxList) so that
#     # build_Tail_Connections can keep them as independent open chains
#     # instead of accidentally chaining ray -> next ray.
#     rayIdxList = []
#     for d in rayPositions:
#         hw = halfWidth(d)
#         nRay = max(round((2 * hw) / ds), 2)
#         yRay = np.linspace(y0 - hw, y0 + hw, nRay)
#         xRay = (x0 + d) * np.ones_like(yRay)
#
#         startIdx = len(xLag)
#         xLag.extend(xRay)
#         yLag.extend(yRay)
#         rayIdxList.append(list(range(startIdx, len(xLag))))
#
#     xLag = np.array(xLag)
#     yLag = np.array(yLag)
#
#     return xLag, yLag, frameIdx, rayIdxList, baseCornerIdx
#
# ---------------------------------------------------------------------------